app:
  build: '.'
  dockerfile: 'DockerfileDev'
  command: 'npm run dev'
  ports:
    - 8080:8080
  environment:
    SECRET: "secret"
    GITHUB_TOKEN:
    SLACK_HOOK:
    SLACK_USERNAME:
    CONFIG_URL:
    CONFIG_PATH: "/home/app/src/example.yaml"
  volumes:
    - './:/home/app/src'
    - '/repos:/repos'
    - '/var/run/docker.sock:/var/run/docker.sock'
    - '$HOME/.docker:/home/app/.docker'
hooklog:
  image: 'firstandthird/httplog'
  ports:
    - 8081:8080
