proxy:
  image: traefik
  command: --web --docker --logLevel=WARN
  ports:
    - "80:80"
    - "8080:8080"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /dev/null:/traefik.toml
app:
  build: '.'
  dockerfile: 'DockerfileDev'
  command: 'npm run dev'
  environment:
    SECRET: "secret"
    GITHUB_TOKEN:
    SLACK_HOOK:
    SLACK_USERNAME:
    CONFIG_URL:
    CONFIG_PATH: 'example.yaml'
  volumes:
    - './:/home/app/src'
    - '/repos:/repos'
    - '/var/run/docker.sock:/var/run/docker.sock'
    - '$HOME/.docker:/home/app/.docker'
  labels:
    - "traefik.frontend.rule=PathPrefix:/"
hooklog:
  image: 'firstandthird/httplog'
  ports:
    - 8080
  labels:
    - "traefik.frontend.rule=PathPrefixStrip:/log"
