app:
  build: '.'
  dockerfile: 'DockerfileDev'
  command: 'npm run dev'
  environment:
    SECRET: "secret"
    GITHUB_TOKEN:
    VIRTUAL_HOST: builder.*
    SLACK_HOOK:
    CONFIG_URL:
    CONFIG_PATH:
  volumes:
    - './:/home/app/src'
    - '/repos:/repos'
    - '/var/run/docker.sock:/var/run/docker.sock'
    - '$HOME/.docker:/home/app/.docker'
hooklog:
  image: 'firstandthird/httplog'
  ports:
    - 8080
  environment:
    VIRTUAL_HOST: 'log.*'
