app:
  build: '.'
  environment:
    SECRET:
    GITHUB_TOKEN:
    DOCKER_AUTH:
    VIRTUAL_HOST: "autobuild.*"
    VERBOSE: 1
    REGISTRY:
    CONFIG_URL:
    CONFIG_PATH:
  volumes:
    - '/var/run/docker.sock:/var/run/docker.sock'
    - './scripts:/scripts'
    - './repos:/repos'
