app:
  build: '.'
  dockerfile: 'DockerfileDev'
  command: 'npm run dev'
  environment:
    SECRET:
    GITHUB_TOKEN:
    VIRTUAL_HOST: "autobuild.*"
    SLACK_HOOK:
    VERBOSE: 1
  volumes:
    - './:/home/app/src'
    - '/var/run/docker.sock:/var/run/docker.sock'
    - './example.yaml:/home/app/src/conf/default-repos.yaml'
    - '$HOME/.docker:/home/app/.docker'
