app:
  build: '.'
  environment:
    SECRET:
    GITHUB_TOKEN:
    DOCKER_AUTH:
    VIRTUAL_HOST: "autobuild.*"
    VERBOSE: 1
    WEBHOOK:
    SLACK_HOOK:
    SLACK_CHANNEL:
    ONLY_TAGS:
    ONLY_BRANCH:
    REGISTRY:
  volumes:
    - '/var/run/docker.sock:/var/run/docker.sock'
    - './scripts:/scripts'
