app:
  build: '.'
  dockerfile: 'DockerfileDev'
  command: 'npm run dev'
  environment:
    SECRET:
    GITHUB_TOKEN:
    VIRTUAL_HOST: "autobuild.*"
    SLACK_HOOK:
    RAPPTOR_CONFIG_URL:
  volumes:
    - './:/home/app/src'
    - '/var/run/docker.sock:/var/run/docker.sock'
    - '$HOME/.docker:/home/app/.docker'
