app:
  build: '.'
  dockerfile: 'DockerfileDev'
  command: 'npm run dev'
  environment:
    SECRET:
    GITHUB_TOKEN:
    VIRTUAL_HOST:
    SLACK_HOOK:
    CONFIG_URL:
    CONFIG_PATH:
  volumes:
    - './:/home/app/src'
    - '/repos:/repos'
    - '/var/run/docker.sock:/var/run/docker.sock'
#     - '$HOME/.docker:/home/app/.docker'
