githubToken: '{{ENV.GITHUB_TOKEN}}'
secret: '{{ENV.SECRET}}'
slackHook: '{{ENV.SLACK_HOOK}}'
plugins:
  hapi-logr:
    reporters:
      logr-slack:
        reporter: 'logr-slack'
        enabled: '{{(slackHook)}}'
        options:
          hideTags: true
          filter:
            - 'builder'
            - 'warning'
            - 'error'
          slackHook: '{{slackHook}}'
          username: 'AutoBuild'
          icon_emoji: ':wrench:'
  hapi-auto-handler:
    _priority: -4
