githubToken: '{{ENV.GITHUB_TOKEN}}'
secret: '{{ENV.SECRET}}'
slackHook: '{{ENV.SLACK_HOOK}}'
configPath: '{{ENV.CONFIG_PATH}}'
configUrl: '{{ENV.CONFIG_URL}}'
plugins:
  hapi-logr:
    reporters:
      logr-slack:
        reporter: 'logr-slack'
        enabled: '{{(slackHook)}}'
        options:
          hideTags: true
          filter:
            - 'success'
            - 'error'
          slackHook: '{{slackHook}}'
          username: '{{ ENV.SLACK_USERNAME || "AutoBuild" }}'
          icon_emoji: ':wrench:'
  hapi-auto-handler:
    _priority: -4
