githubToken: '{{ENV.GITHUB_TOKEN}}'
secret: '{{ENV.SECRET}}'
slackHook: '{{ENV.SLACK_HOOK}}'
configPath: '{{ENV.CONFIG_PATH}}'
configUrl: '{{ENV.CONFIG_URL}}'
builder:
  memLimit: '{{ENV.MEM_LIMIT}}'
  cpuShares: '{{ENV.CPU_SHARES}}'
plugins:
  hapi-oppsy:
    _enabled: false
  hapi-favicon:
  hapi-logr:
    reporters:
      logr-slack:
        reporter: 'logr-slack'
        enabled: '{{(slackHook)}}'
        options:
          hideTags: true
          filter:
            - 'success'
            - 'error'
          slackHook: '{{slackHook}}'
          username: '{{ ENV.SLACK_USERNAME || "AutoBuild" }}'
          iconEmoji: ':wrench:'
