githubToken: '{{getEnv("GITHUB_TOKEN")}}'
secret: '{{getEnv("SECRET")}}'
slackHook: '{{getEnv("SLACK_HOOK", "")}}'
configPath: '{{getEnv("CONFIG_PATH")}}'
builder:
  memLimit: '{{getEnv("MEM_LIMIT", "")}}'
  cpuShares: '{{getEnv("CPU_SHARES", "")}}'
plugins:
  hapi-oppsy:
    _enabled: false
  hapi-favicon:
  hapi-logr:
    reporters:
      logr-slack:
        reporter: 'logr-slack'
        options:
          enabled: '{{envExists("SLACK_HOOK")}}'
          hideTags: true
          filter:
            - 'success'
            - 'error'
          slackHook: '{{slackHook}}'
          username: '{{ getEnv("SLACK_USERNAME", "AutoBuild") }}'
          iconEmoji: ':wrench:'
