#!/bin/bash

log() {
  if [[ "$DEBUG" == "1" ]]; then
    echo $@
  fi
}

if [[ -n "$WEBHOOK" ]]; then
  log "triggering hook: $WEBHOOK"
  curl \
    --fail --silent --show-error \
   -H "Content-Type: application/json" \
   -X POST \
   -d "{\"repo\":\"$GITHUB_REPO\",\"user\":\"$GITHUB_USER\",\"branch\":\"$GITHUB_BRANCH\",\"event\":\"delete\"}" \
   $WEBHOOK > /dev/null

  if [[ "$?" != 0 ]]; then
    log "!Hook errored"
  fi
fi
