#!/bin/bash

#build repo
BUILDER="firstandthird/builder:0.0.10"
docker pull $BUILDER > /dev/null 2>&1
docker run \
  --rm \
  -e USER=$GITHUB_USER \
  -e REPO=$GITHUB_REPO \
  -e BRANCH=$GITHUB_BRANCH \
  -e TOKEN=$GITHUB_TOKEN \
  -e TAG=$DOCKER_TAG \
  -e DEBUG=1 \
  -e PUSH=1 \
  -e PUSH_LATEST=1 \
  -e REGISTRY=$REGISTRY \
  -e DOCKER_AUTH=$DOCKER_AUTH \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v /repos:/repos \
  ${BUILDER}

if [[ "$?" != 0 ]]; then
  echo "there was an error building"
  #post2slack --tags error --message "$GITHUB_REPO#$GITHUB_BRANCH failed to build $IMAGE"
  exit 1
fi
