#!/bin/bash

if [[ "$ONLY_TAGS" == "1" ]]; then
  exit 0
fi

if [[ -n "$ONLY_BRANCH" && "$ONLY_BRANCH" != "$GITHUB_BRANCH" ]]; then
  echo "looking for $ONLY_BRANCH, got $GITHUB_BRANCH"
  exit 0
fi

bash /scripts/lib/build
